<?php

namespace orion\option_pages;

class Orion_Email_Marketing_Settings {
	public static function start(): void {
		add_action( 'acf/init', self::acf_init( ... ) );
		add_action( 'acf/include_fields', self::acf_include_fields( ... ) );
	}

	public static function acf_init(): void {
		acf_add_options_page( array(
			'page_title'  => esc_html__( 'Marketing Settings', 'orion' ),
			'menu_slug'   => 'orion-marketing',
			'menu_title'  => esc_html__( 'Marketing', 'orion' ),
			'parent_slug' => 'orion',
			'position'    => 3,
			'capability'  => 'manage_options',
		) );
	}

	public static function acf_include_fields(): void {
		acf_add_local_field_group( array(
			'key'                    => 'group_6001d78842be4',
			'title'                  => esc_html__( 'Marketing', 'orion' ),
			'fields'                 => array(
				array(
					'key'                 => 'field_660bd634c43ee',
					'label'               => esc_html__( 'URLs', 'orion' ),
					'name'                => '',
					'aria-label'          => '',
					'type'                => 'tab',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 1,
					'placement'           => 'top',
					'endpoint'            => 0,
				),
				array(
					'key'                 => 'field_6607f3e1dc0ba',
					'label'               => esc_html__( 'Calendly URL', 'orion' ),
					'name'                => 'calendly_url',
					'aria-label'          => '',
					'type'                => 'text',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'maxlength'           => '',
					'placeholder'         => '',
					'prepend'             => '',
					'append'              => '',
				),
				array(
					'key'                 => 'field_660b3058e6cfb',
					'label'               => esc_html__( 'Get your guide URL', 'orion' ),
					'name'                => 'get_your_guide_url',
					'aria-label'          => '',
					'type'                => 'text',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'maxlength'           => '',
					'placeholder'         => '',
					'prepend'             => '',
					'append'              => '',
				),
				array(
					'key'                 => 'field_660bd640c43ef',
					'label'               => esc_html__( 'Email', 'orion' ),
					'name'                => '',
					'aria-label'          => '',
					'type'                => 'tab',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 1,
					'placement'           => 'top',
					'endpoint'            => 0,
				),
				array(
					'key'                 => 'field_660bd651c43f0',
					'label'               => esc_html__( 'From Email Address', 'orion' ),
					'name'                => 'from_email_address',
					'aria-label'          => '',
					'type'                => 'text',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'maxlength'           => '',
					'placeholder'         => '',
					'prepend'             => '',
					'append'              => '',
				),
				array(
					'key'                 => 'field_660bd65cc43f1',
					'label'               => esc_html__( 'From Name', 'orion' ),
					'name'                => 'from_name',
					'aria-label'          => '',
					'type'                => 'text',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'maxlength'           => '',
					'placeholder'         => '',
					'prepend'             => '',
					'append'              => '',
				),
			),
			'location'               => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-marketing',
					),
				),
			),
			'menu_order'             => 1,
			'position'               => 'acf_after_title',
			'style'                  => 'default',
			'label_placement'        => 'top',
			'instruction_placement'  => 'field',
			'hide_on_screen'         => '',
			'active'                 => true,
			'description'            => '',
			'show_in_rest'           => 1,
			'acfml_field_group_mode' => 'translation',
		) );

		acf_add_local_field_group( array(
			'key'                    => 'group_660bdc5a9332e',
			'title'                  => esc_html__( 'Email Campaigns Templates', 'orion' ),
			'fields'                 => array(
				array(
					'key'                 => 'field_660bd74763050',
					'label'               => esc_html__( 'Campaign One', 'orion' ),
					'name'                => '',
					'aria-label'          => '',
					'type'                => 'tab',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 1,
					'placement'           => 'top',
					'endpoint'            => 1,
				),
				array(
					'key'                 => 'field_660bdbe84a4cf',
					'label'               => esc_html__( 'Campaign One Subject', 'orion' ),
					'name'                => 'campaign_one_subject_',
					'aria-label'          => '',
					'type'                => 'text',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'maxlength'           => '',
					'placeholder'         => '',
					'prepend'             => '',
					'append'              => '',
				),
				array(
					'key'                 => 'field_660bd66ec43f2',
					'label'               => esc_html__( 'Campaign One Template', 'orion' ),
					'name'                => 'campaign_one_template',
					'aria-label'          => '',
					'type'                => 'wysiwyg',
					'instructions'        => '',
					'required'            => 0,
					'conditional_logic'   => 0,
					'wrapper'             => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'wpml_cf_preferences' => 2,
					'default_value'       => '',
					'tabs'                => 'all',
					'toolbar'             => 'full',
					'media_upload'        => 1,
					'delay'               => 0,
				),
			),
			'location'               => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-marketing',
					),
				),
			),
			'menu_order'             => 2,
			'position'               => 'normal',
			'style'                  => 'default',
			'label_placement'        => 'top',
			'instruction_placement'  => 'label',
			'hide_on_screen'         => '',
			'active'                 => true,
			'description'            => '',
			'show_in_rest'           => 0,
			'acfml_field_group_mode' => 'translation',
		) );
	}
}