<?php

namespace orion\option_pages;

class Orion_Registration_Fields {
	public static function start(): void {
		add_action( 'acf/init', self::acf_init( ... ) );
		add_action( 'acf/include_fields', self::acf_include_fields( ... ) );
	}

	public static function acf_init() {
		acf_add_options_page( array(
			'page_title'  => esc_html__( 'Registration fields', 'orion' ),
			'menu_slug'   => 'orion-registration-fields',
			'parent_slug' => 'orion',
			'menu_title'  => esc_html__( 'Registration fields', 'orion' ),
			'position'    => 2,
			'redirect'    => false,
			'capability'  => 'manage_options',
			'post_id'     => 914,
		) );
	}

	public static function acf_include_fields(): void {
		acf_add_local_field_group( array(
			'key'                   => 'group_664289376d424',
			'title'                 => 'Registration fields',
			'fields'                => array(
				array(
					'key'               => 'field_66428a19cd892',
					'label'             => esc_html__( 'Hide username field', 'orion' ),
					'name'              => 'registration_field_hide_username_field',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_66428d737b9a8',
					'label'             => esc_html__( 'Registration custom fields', 'orion' ),
					'name'              => 'registration_custom_fields',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'row',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 0,
					'collapsed'         => '',
					'button_label'      => 'Add custom Field',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_66429cdbfbc3a',
							'label'             => esc_html__( 'Type', 'orion' ),
							'name'              => 'registration_custom_field_type',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'text'     => 'Text',
								'select'   => 'Select',
								'email'    => 'Email',
								'checkbox' => 'Checkbox',
								'radio'    => 'Radio',
							),
							'default_value'     => false,
							'return_format'     => 'value',
							'multiple'          => 0,
							'allow_null'        => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_66428bfbdff6b',
							'label'             => esc_html__( 'Field name', 'orion' ),
							'name'              => 'registration_custom_field_name',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_66428c0bdff6c',
							'label'             => esc_html__( 'Field size', 'orion' ),
							'name'              => 'registration_custom_field_size',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'25%'  => '25%',
								'33%'  => '33%',
								'50%'  => '50%',
								'66%'  => '66%',
								'75%'  => '75%',
								'100%' => '100%',
							),
							'default_value'     => '100%',
							'return_format'     => 'value',
							'multiple'          => 0,
							'allow_null'        => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_66429d26fbc3b',
							'label'             => esc_html__( 'Options', 'orion' ),
							'name'              => 'registration_custom_field_select_options',
							'aria-label'        => '',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_66429cdbfbc3a',
										'operator' => '==',
										'value'    => 'select',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'row',
							'min'               => 0,
							'max'               => 0,
							'collapsed'         => '',
							'button_label'      => 'Add Option',
							'rows_per_page'     => 20,
							'sub_fields'        => array(
								array(
									'key'               => 'field_66429d89fbc3c',
									'label'             => esc_html__( 'Option', 'orion' ),
									'name'              => 'option',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'maxlength'         => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'parent_repeater'   => 'field_66429d26fbc3b',
								),
							),
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_66439b26dfc1f',
							'label'             => esc_html__( 'Value', 'orion' ),
							'name'              => 'registration_custom_field_value',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_66429cdbfbc3a',
										'operator' => '==',
										'value'    => 'checkbox',
									),
								),
								array(
									array(
										'field'    => 'field_66429cdbfbc3a',
										'operator' => '==',
										'value'    => 'radio',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_6642a4acc659a',
							'label'             => esc_html__( 'Required', 'orion' ),
							'name'              => 'registration_custom_field_required',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
							'ui'                => 1,
							'parent_repeater'   => 'field_66428d737b9a8',
						),
						array(
							'key'               => 'field_6643a24697b57',
							'label'             => esc_html__( 'Required validation text', 'orion' ),
							'name'              => 'registration_custom_field_required_validation_text',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6642a4acc659a',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => 'The %s field is required',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_66428d737b9a8',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-registration-fields',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );
	}
}