<?php

namespace orion\option_pages;

// @package orion

class Orion_Login_Settings {
	public static function start(): void {
		add_action( 'acf/init', self::acf_init( ... ) );
		add_action( 'init', self::init( ... ) );
		add_action( 'acf/include_fields', self::acf_include_fields( ... ) );
	}

	public static function init(): void {
		register_post_type( 'setting', array(
			'labels'              => array(
				'name'                     => esc_html__( 'Settings', 'orion' ),
				'singular_name'            => esc_html__( 'Setting', 'orion' ),
				'menu_name'                => esc_html__( 'Settings', 'orion' ),
				'all_items'                => esc_html__( 'All Settings', 'orion' ),
				'edit_item'                => esc_html__( 'Edit Setting', 'orion' ),
				'view_item'                => esc_html__( 'View Setting', 'orion' ),
				'view_items'               => esc_html__( 'View Settings', 'orion' ),
				'add_new_item'             => esc_html__( 'Add New Setting', 'orion' ),
				'add_new'                  => esc_html__( 'Add New Setting', 'orion' ),
				'new_item'                 => esc_html__( 'New Setting', 'orion' ),
				'parent_item_colon'        => esc_html__( 'Parent Setting:', 'orion' ),
				'search_items'             => esc_html__( 'Search Settings', 'orion' ),
				'not_found'                => esc_html__( 'No settings found', 'orion' ),
				'not_found_in_trash'       => esc_html__( 'No settings found in Trash', 'orion' ),
				'archives'                 => esc_html__( 'Setting Archives', 'orion' ),
				'attributes'               => esc_html__( 'Setting Attributes', 'orion' ),
				'insert_into_item'         => esc_html__( 'Insert into setting', 'orion' ),
				'uploaded_to_this_item'    => esc_html__( 'Uploaded to this setting', 'orion' ),
				'filter_items_list'        => esc_html__( 'Filter settings list', 'orion' ),
				'filter_by_date'           => esc_html__( 'Filter settings by date', 'orion' ),
				'items_list_navigation'    => esc_html__( 'Settings list navigation', 'orion' ),
				'items_list'               => esc_html__( 'Settings list', 'orion' ),
				'item_published'           => esc_html__( 'Setting published.', 'orion' ),
				'item_published_privately' => esc_html__( 'Setting published privately.', 'orion' ),
				'item_reverted_to_draft'   => esc_html__( 'Setting reverted to draft.', 'orion' ),
				'item_scheduled'           => esc_html__( 'Setting scheduled.', 'orion' ),
				'item_updated'             => esc_html__( 'Setting updated.', 'orion' ),
				'item_link'                => esc_html__( 'Setting Link', 'orion' ),
				'item_link_description'    => esc_html__( 'A link to a setting.', 'orion' ),
			),
			'public'              => false,
			'exclude_from_search' => false,
			'show_in_menu'        => true,
			'show_in_rest'        => false,
			'supports'            => array(
				0 => 'title',
			),
			'rewrite'             => array(
				'with_front' => false,
				'pages'      => false,
			),
			'delete_with_user'    => false,
		) );
	}

	public static function acf_init(): void {
		acf_add_options_page( array(
			'page_title'  => 'Login settings',
			'menu_slug'   => 'orion-login-settings',
			'parent_slug' => 'orion',
			'menu_title'  => esc_html__( 'Login settings', 'orion' ),
			'position'    => 1,
			'redirect'    => false,
			'capability'  => 'manage_options',
		) );
	}

	public static function acf_include_fields(): void {
		acf_add_local_field_group( array(
			'key'                   => 'group_66425dcf138ca',
			'title'                 => 'Login Settings',
			'fields'                => array(
				array(
					'key'               => 'field_663b350568f02',
					'label'             => esc_html__( 'Customize login page', 'orion' ),
					'name'              => 'customize_login_page',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
//              @todo make this work correctly
//				array(
//					'key'               => 'field_663b82445334b',
//					'label'             => esc_html__( 'Custom Login URL', 'orion' ),
//					'name'              => 'custom_login_url',
//					'aria-label'        => '',
//					'type'              => 'true_false',
//					'instructions'      => '',
//					'required'          => 0,
//					'conditional_logic' => 0,
//					'wrapper'           => array(
//						'width' => '25',
//						'class' => '',
//						'id'    => '',
//					),
//					'message'           => '',
//					'default_value'     => 0,
//					'ui_on_text'        => '',
//					'ui_off_text'       => '',
//					'ui'                => 1,
//				),
				array(
					'key'               => 'field_663b719832286',
					'label'             => esc_html__( 'Customize labels', 'orion' ),
					'name'              => 'customize_labels',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663a36573882b',
					'label'             => esc_html__( 'Authenticated Users Only', 'orion' ),
					'name'              => 'authenticated_users_only',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_664262dcaee65',
			'title'                 => 'Login Layout & Fonts',
			'fields'                => array(
				array(
					'key'               => 'field_663d386bf297b',
					'label'             => esc_html__( 'Layout', 'orion' ),
					'name'              => 'login_layout',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => 'Sets the position of the login/register/forgot password box',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'center' => 'Center',
						'left'   => 'Left',
						'right'  => 'Right',
					),
					'default_value'     => 'center',
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 1,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_663cd77797e9a',
					'label'             => esc_html__( 'Font family', 'orion' ),
					'name'              => 'font-family',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 1,
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 2,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_66425eabf0873',
			'title'                 => 'Login Colors',
			'fields'                => array(
				array(
					'key'               => 'field_66423032fe379',
					'label'             => esc_html__( 'Background', 'orion' ),
					'name'              => 'form_background_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_66422decfe374',
					'label'             => esc_html__( 'Border Color', 'orion' ),
					'name'              => 'border_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_66423e1f1087c',
					'label'             => esc_html__( 'Field Border Color', 'orion' ),
					'name'              => 'form_field_border_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663b309b48deb',
					'label'             => esc_html__( 'Submit button background color', 'orion' ),
					'name'              => 'submit_button_bg_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663a96296394d',
					'label'             => esc_html__( 'Submit button text color', 'orion' ),
					'name'              => 'submit_button_text_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_66424f89e8b7f',
					'label'             => esc_html__( 'Default button background color', 'orion' ),
					'name'              => 'default_button_background_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_66424fa0e8b80',
					'label'             => esc_html__( 'Default button text color', 'orion' ),
					'name'              => 'default_button_text_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663b306748de8',
					'label'             => esc_html__( 'Background color', 'orion' ),
					'name'              => 'background_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663a95b868ba1',
					'label'             => esc_html__( 'Text Color', 'orion' ),
					'name'              => 'text_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663a95cc68ba2',
					'label'             => esc_html__( 'Link Color', 'orion' ),
					'name'              => 'link_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'enable_opacity'    => 1,
					'return_format'     => 'string',
				),
				array(
					'key'               => 'field_663d3dd7b89b0',
					'label'             => esc_html__( 'BG Color', 'orion' ),
					'name'              => 'container_background_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '#FFFFFF',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 3,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_66425f788818c',
			'title'                 => 'Login Dimensions',
			'fields'                => array(
				array(
					'key'               => 'field_6642499bec3a4',
					'label'             => esc_html__( 'Form width', 'orion' ),
					'name'              => 'form_width',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_664249b8ec3a5',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'form_width_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_66422e1cfe375',
					'label'             => esc_html__( 'Border width', 'orion' ),
					'name'              => 'border_width',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_66422e2efe376',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'border_width_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_664234d2dff8b',
					'label'             => esc_html__( 'Form padding', 'orion' ),
					'name'              => 'form_padding',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_664234f0dff8c',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'form_padding_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_663c98a3a4a39',
					'label'             => esc_html__( 'Container width', 'orion' ),
					'name'              => 'container_width',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '20',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 320,
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663c9911a4a3a',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'container_width_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
						'vw'  => 'vw',
					),
					'default_value'     => 'px',
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 4,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_664260ae5dfc8',
			'title'                 => 'Login Logo Settings',
			'fields'                => array(
				array(
					'key'               => 'field_663a3ba8a4ca8',
					'label'             => esc_html__( 'Use Custom Logo', 'orion' ),
					'name'              => 'use_custom_logo',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663a3c86c7fd8',
					'label'             => esc_html__( 'Logo from Theme Settings', 'orion' ),
					'name'              => 'logo_from_theme_settings',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663a3c4ec7fd7',
					'label'             => esc_html__( '', 'orion' ),
					'name'              => '',
					'aria-label'        => '',
					'type'              => 'message',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_663a3ba8a4ca8',
								'operator' => '==',
								'value'    => '1',
							),
							array(
								'field'    => 'field_663a3c86c7fd8',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'message'           => 'Use the value of the custom logo in the <a href="http://localhost:10028/wp-admin/customize.php?return=%2Fwp-admin%2Fpost.php%3Fpost%3D40%26action%3Dedit">Site Editing</a>',
					'new_lines'         => 'wpautop',
					'esc_html'          => 0,
				),
				array(
					'key'               => 'field_663a3bfba4ca9',
					'label'             => esc_html__( 'Custom Logo', 'orion' ),
					'name'              => 'custom_logo',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_663a3ba8a4ca8',
								'operator' => '==',
								'value'    => '1',
							),
							array(
								'field'    => 'field_663a3c86c7fd8',
								'operator' => '!=',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'url',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium',
				),
				array(
					'key'               => 'field_663b324dae82b',
					'label'             => esc_html__( 'Logo width', 'orion' ),
					'name'              => 'logo_width',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 300,
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '0.01',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b3292ae82c',
					'label'             => esc_html__( 'Logo width unit', 'orion' ),
					'name'              => 'logo_width_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
						'vw'  => 'vw',
					),
					'default_value'     => 'px',
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_663d353b9cab8',
					'label'             => esc_html__( 'Logo height', 'orion' ),
					'name'              => 'logo_height',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'auto',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b32ccae82e',
					'label'             => esc_html__( 'Logo height unit', 'orion' ),
					'name'              => 'logo_height_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '12.5',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
						'vw'  => 'vw',
					),
					'default_value'     => 'px',
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 4,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_6642625a8ada3',
			'title'                 => 'Login Background Image',
			'fields'                => array(
				array(
					'key'               => 'field_663b3995b7651',
					'label'             => esc_html__( 'Body Background image', 'orion' ),
					'name'              => 'body_background_image',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'uploadedTo',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'preview_size'      => 'medium_large',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 5,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_6642602722fb7',
			'title'                 => 'Login Borders',
			'fields'                => array(
				array(
					'key'               => 'field_66423b8dc8b1e',
					'label'             => esc_html__( 'Border radius', 'orion' ),
					'name'              => 'form_border_radius',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_66423b40c8b1d',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'form_border_radius_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_66423efee79d4',
					'label'             => esc_html__( 'Field border', 'orion' ),
					'name'              => 'form_field_border',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_66423f0ce79d5',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'form_field_border_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_66423cf6354a7',
					'label'             => esc_html__( 'Field radius', 'orion' ),
					'name'              => 'form_field_border_radius',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_66423d11354a8',
					'label'             => esc_html__( 'Unit', 'orion' ),
					'name'              => 'form_field_border_radius_unit',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '10',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'%'   => '%',
						'px'  => 'px',
						'em'  => 'em',
						'rem' => 'rem',
					),
					'default_value'     => false,
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 5,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_6642639e6808f',
			'title'                 => 'Login Custom Labels',
			'fields'                => array(
				array(
					'key'               => 'field_663b727d32288',
					'label'             => esc_html__( 'Username', 'orion' ),
					'name'              => 'label_username',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Username',
					'maxlength'         => '',
					'placeholder'       => 'Username',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b729d32289',
					'label'             => esc_html__( 'Password', 'orion' ),
					'name'              => 'label_password',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Password',
					'maxlength'         => '',
					'placeholder'       => 'Password',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b72b13228a',
					'label'             => esc_html__( 'Remember Me', 'orion' ),
					'name'              => 'label_remember',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Remember Me',
					'maxlength'         => '',
					'placeholder'       => 'Remember Me',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663cc60a79ac9',
					'label'             => esc_html__( 'Login link', 'orion' ),
					'name'              => 'label_login_link',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Login',
					'maxlength'         => '',
					'placeholder'       => 'Log In',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b72db3228b',
					'label'             => esc_html__( 'Register link', 'orion' ),
					'name'              => 'label_register_link',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Register',
					'maxlength'         => '',
					'placeholder'       => 'Log In',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663cc5ee79ac8',
					'label'             => esc_html__( 'Forgot password link', 'orion' ),
					'name'              => 'label_forgot_password_link',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Lost your password?',
					'maxlength'         => '',
					'placeholder'       => 'Forgot your password?',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663d41820f13f',
					'label'             => esc_html__( 'Show back to blog', 'orion' ),
					'name'              => 'show_back_to_blog',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui_on_text'        => esc_html__( 'Yes', 'orion' ),
					'ui_off_text'       => esc_html__( 'No', 'orion' ),
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663cc62279aca',
					'label'             => esc_html__( 'Back to blog', 'orion' ),
					'name'              => 'label_back_to_block',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Back to %s%',
					'maxlength'         => '',
					'placeholder'       => 'Back to %s',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663d41820f13e',
					'label'             => esc_html__( 'Show privacy policy link', 'orion' ),
					'name'              => 'show_privacy_policy_page_link',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui_on_text'        => esc_html__( 'Yes', 'orion' ),
					'ui_off_text'       => esc_html__( 'No', 'orion' ),
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663d053688322',
					'label'             => esc_html__( 'Registration message', 'orion' ),
					'name'              => 'registration_message',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Register For This Site',
					'maxlength'         => '',
					'placeholder'       => 'Register For This Site',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_663d05a7c0bd8',
					'label'             => esc_html__( 'Login header message', 'orion' ),
					'name'              => 'login_header_message',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Log In',
					'maxlength'         => '',
					'placeholder'       => 'Log In',
					'prepend'           => '',
					'append'            => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 6,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_664263f63fb35',
			'title'                 => 'Login Custom URLs',
			'fields'                => array(
				array(
					'key'               => 'field_663b8c57e3a75',
					'label'             => esc_html__( 'Login page', 'orion' ),
					'name'              => 'login_url',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Add the custom link you without trailing or starting slashes',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'login',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '/',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b973cfb46e',
					'label'             => esc_html__( 'Register page', 'orion' ),
					'name'              => 'register_url',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Add the custom link you without trailing or starting slashes',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'register',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '/',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b9751fb470',
					'label'             => esc_html__( 'Lost password page', 'orion' ),
					'name'              => 'lost_password_url',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Add the custom link you without trailing or starting slashes',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'lost-password',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '/',
					'append'            => '',
				),
				array(
					'key'               => 'field_663b975bfb471',
					'label'             => esc_html__( 'Reset password page', 'orion' ),
					'name'              => 'reset_password_url',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Add the custom link you without trailing or starting slashes',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'reset-password',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '/',
					'append'            => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 7,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => false,
			'description'           => '',
			'show_in_rest'          => 0,
		) );

		acf_add_local_field_group( array(
			'key'                   => 'group_664265e27f7d5',
			'title'                 => 'Login Messages',
			'fields'                => array(
				array(
					'key'               => 'field_663d0a028c626',
					'label'             => esc_html__( 'Position', 'orion' ),
					'name'              => 'message_position',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'default'       => 'Default',
						'top-right'     => 'Top right',
						'top-center'    => 'Top center',
						'top-left'      => 'Top left',
						'bottom-right'  => 'Bottom right',
						'bottom-center' => 'Bottom center',
						'bottom-left'   => 'Bottom left',
					),
					'default_value'     => 'default',
					'return_format'     => 'value',
					'multiple'          => 0,
					'allow_null'        => 0,
					'ui'                => 0,
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_663d2c8bf2959',
					'label'             => esc_html__( 'Use generic error message', 'orion' ),
					'name'              => 'use_generic_error_message',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_663d2cc5f295a',
					'label'             => esc_html__( 'Generic error message', 'orion' ),
					'name'              => 'generic_error_message',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => 'Invalid credentials, please try again',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'orion-login-settings',
					),
				),
			),
			'menu_order'            => 8,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		) );
	}
}