on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ORION_FTP_SERVER }}
          username: ${{ secrets.ORION_FTP_USERNAME }}
          password: ${{ secrets.ORION_FTP_PASSWORD }}
          "server-dir": ./wp-content/plugins/orion/